name: InvisiThreat Security Scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Allow unsigned scripts
        run: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Security Scanner
        run: python run_scan.py
